/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Menggunakan project Supabase demo untuk testing
export const projectId = "vaxeekwomckvlbcsyjje"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZheGVla3dvbWNrdmxiY3N5amplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODA3NDMsImV4cCI6MjA3MDA1Njc0M30.l1GpFH7a7WVw2Sl9k5R8YvorRonC1Kf5UmYpTb9Kj2o"
